# below three dashes signifies that it is a YAML file
---
name: Checks # name of workflow

on: [push] # trigger, So we say this particular Action to run on PUSH event

jobs:
  test-lint: #ID of the job
    name: Test and Lint
    runs-on: ubuntu-20.04 #RUNNER(Operating system that will be running our workflow on an event)
    steps:
      - name: Login to Docker Hub
        # Below is the action you can specify, either you create your own actions or we can RE-USE existing actions that are used for particular jobs 
        uses: docker/login-action@v1 # uses allow you to use another pre-maid ACTION that's provided in github action Respository
        with: # pasing parameters which passes to Docker LogIN action
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
      - name: Checkout # checkout he code that it is available for next step
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test" # command to run UNIT TEST on project
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"